# Generated by Django 4.2 on 2023-04-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Optimizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locations', models.JSONField(default=dict)),
                ('depot', models.IntegerField(default=0)),
                ('num_vehicles', models.IntegerField(default=1)),
                ('matrix', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
